name: 'Auto update flake lock file'

on:
  workflow_dispatch:
  schedule:
    - cron: '* */4 * * *'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

    - name: Update flake.lock
      run: nix flake update

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update `flake.lock` file.
        file_pattern: flake.lock
